import { MealPlanType, Recipe, ShoppingListItem, ShoppingListType } from "./types";

export const mealPlanData: MealPlanType[] = [
  {
    id: 1,
    day: "Monday",
    breakfast: ["Oatmeal with berries"],
    lunch: ["Grilled chicken salad"],
    dinner: ["Salmon with quinoa"],
    snacks: ["Greek yogurt", "Mixed nuts"]
  },
  {
    id: 2,
    day: "Tuesday",
    breakfast: ["Scrambled eggs with spinach"],
    lunch: ["Turkey and avocado wrap"],
    dinner: ["Stir-fried tofu with vegetables and brown rice"],
    snacks: ["Apple slices with peanut butter", "Carrot sticks"]
  },
  {
    id: 3,
    day: "Wednesday",
    breakfast: ["Greek yogurt parfait with granola"],
    lunch: ["Quinoa and chickpea salad"],
    dinner: ["Grilled shrimp tacos with cabbage slaw"],
    snacks: ["Protein bar", "Handful of almonds"]
  },
  {
    id: 4,
    day: "Thursday",
    breakfast: ["Smoothie with banana, spinach, and protein powder"],
    lunch: ["Lentil soup with whole grain bread"],
    dinner: ["Baked chicken breast with sweet potato and green beans"],
    snacks: ["Rice cakes with hummus", "Berries"]
  },
  {
    id: 5,
    day: "Friday",
    breakfast: ["Whole grain toast with avocado and poached egg"],
    lunch: ["Tuna salad with mixed greens"],
    dinner: ["Beef stir-fry with vegetables and brown rice"],
    snacks: ["Trail mix", "Cottage cheese with pineapple"]
  },
  {
    id: 6,
    day: "Saturday",
    breakfast: ["Pancakes with fresh fruit"],
    lunch: ["Grilled veggie and hummus wrap"],
    dinner: ["Baked cod with roasted vegetables"],
    snacks: ["Celery sticks with peanut butter", "Protein shake"]
  },
  {
    id: 7,
    day: "Sunday",
    breakfast: ["Bagel with smoked salmon and cream cheese"],
    lunch: ["Caprese salad with whole grain bread"],
    dinner: ["Roast chicken with mashed cauliflower"],
    snacks: ["Dark chocolate square", "Fruit salad"]
  }
];

export const shoppingListData: ShoppingListType[] = [
  {
    id: 1,
    name: "Salmon fillets",
    amount: "2 lbs"
  },
  {
    id: 2,
    name: "Quinoa",
    amount: "1 bag"
  },
  {
    id: 3,
    name: "Mixed berries",
    amount: "2 cups"
  },
  {
    id: 4,
    name: "Greek yogurt",
    amount: "32 oz"
  },
  {
    id: 5,
    name: "Avocados",
    amount: "4 pieces"
  },
  {
    id: 6,
    name: "Eggs",
    amount: "1 dozen"
  },
  {
    id: 7,
    name: "Spinach",
    amount: "1 bag"
  },
  {
    id: 8,
    name: "Chicken breasts",
    amount: "2 lbs"
  },
  {
    id: 9,
    name: "Whole grain bread",
    amount: "1 loaf"
  }
];

export const mealTemplates = [
  { name: "Mediterranean Week", description: "Fresh, healthy Mediterranean cuisine", meals: 21, rating: 4.8 },
  { name: "Quick & Easy", description: "30-minute meals for busy schedules", meals: 18, rating: 4.6 },
  { name: "Vegetarian Delight", description: "Plant-based meals full of flavor", meals: 20, rating: 4.7 },
  { name: "Family Favorites", description: "Kid-friendly meals the whole family loves", meals: 19, rating: 4.5 },
  { name: "Keto Friendly", description: "Low-carb, high-fat meal plans", meals: 17, rating: 4.4 },
  { name: "Meal Prep Master", description: "Batch cooking for the week ahead", meals: 15, rating: 4.9 },
]

export const popularRecipes = [
  { name: "Chicken Teriyaki Bowl", time: "25 min", difficulty: "Easy", rating: 4.8 },
  { name: "Mediterranean Pasta", time: "20 min", difficulty: "Easy", rating: 4.7 },
  { name: "Beef Stir Fry", time: "15 min", difficulty: "Medium", rating: 4.6 },
  { name: "Veggie Burger", time: "30 min", difficulty: "Medium", rating: 4.5 },
  { name: "Fish & Chips", time: "35 min", difficulty: "Hard", rating: 4.4 },
  { name: "Taco Tuesday", Fime: "20 min", difficulty: "Easy", rating: 4.9 },
];

export const recipes: Recipe[] = [
  {
    id: "1",
    name: "Mediterranean Quinoa Bowl",
    description: "A healthy and colorful bowl packed with fresh vegetables, quinoa, and a tangy lemon dressing.",
    image: "/placeholder.svg?height=200&width=300",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "easy",
    rating: 4.8,
    reviews: 124,
    category: "lunch",
    tags: ["vegetarian", "gluten-free", "healthy"],
    calories: 420,
    protein: 15,
    carbs: 58,
    fat: 12,
    ingredients: [
      "1 cup quinoa",
      "2 cups vegetable broth",
      "1 cucumber, diced",
      "2 tomatoes, chopped",
      "1/2 red onion, sliced",
      "1/4 cup kalamata olives",
      "1/4 cup feta cheese",
      "2 tbsp olive oil",
      "1 lemon, juiced",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Cook quinoa in vegetable broth according to package directions.",
      "While quinoa cooks, prepare vegetables by dicing cucumber and chopping tomatoes.",
      "Make dressing by whisking together olive oil, lemon juice, salt, and pepper.",
      "Combine cooked quinoa with vegetables in a large bowl.",
      "Add olives and feta cheese, then drizzle with dressing.",
      "Toss gently and serve immediately or chill for later.",
    ],
    isFavorite: true,
  },
  {
    id: "2",
    name: "Honey Garlic Salmon",
    description: "Perfectly glazed salmon with a sweet and savory honey garlic sauce, ready in under 30 minutes.",
    image: "/placeholder.svg?height=200&width=300",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "medium",
    rating: 4.9,
    reviews: 89,
    category: "dinner",
    tags: ["gluten-free", "dairy-free", "high-protein"],
    calories: 380,
    protein: 35,
    carbs: 18,
    fat: 18,
    ingredients: [
      "2 salmon fillets",
      "3 cloves garlic, minced",
      "1/4 cup honey",
      "2 tbsp soy sauce",
      "1 tbsp olive oil",
      "1 tsp ginger, grated",
      "Green onions for garnish",
    ],
    instructions: [
      "Heat olive oil in a large skillet over medium-high heat.",
      "Season salmon with salt and pepper, then cook for 4-5 minutes per side.",
      "Remove salmon and set aside.",
      "In the same pan, add garlic and ginger, cook for 30 seconds.",
      "Add honey and soy sauce, simmer until thickened.",
      "Return salmon to pan and coat with glaze.",
      "Garnish with green onions and serve.",
    ],
    isFavorite: false,
  },
  {
    id: "3",
    name: "Chocolate Chip Banana Bread",
    description: "Moist and delicious banana bread loaded with chocolate chips - perfect for breakfast or dessert.",
    image: "/placeholder.svg?height=200&width=300",
    prepTime: 15,
    cookTime: 60,
    servings: 8,
    difficulty: "easy",
    rating: 4.7,
    reviews: 156,
    category: "desserts",
    tags: ["vegetarian", "comfort-food"],
    calories: 285,
    protein: 4,
    carbs: 45,
    fat: 11,
    ingredients: [
      "3 ripe bananas, mashed",
      "1/3 cup melted butter",
      "3/4 cup sugar",
      "1 egg, beaten",
      "1 tsp vanilla extract",
      "1 tsp baking soda",
      "Pinch of salt",
      "1 1/2 cups flour",
      "1/2 cup chocolate chips",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C).",
      "Mix mashed bananas with melted butter in a large bowl.",
      "Add sugar, egg, and vanilla, mix well.",
      "Sprinkle baking soda and salt over mixture, then mix.",
      "Add flour and mix until just combined.",
      "Fold in chocolate chips.",
      "Pour into greased loaf pan and bake for 60 minutes.",
      "Cool before slicing.",
    ],
    isFavorite: true,
  },
  {
    id: "4",
    name: "Avocado Toast Supreme",
    description: "Elevated avocado toast with everything bagel seasoning, cherry tomatoes, and a perfectly poached egg.",
    image: "/placeholder.svg?height=200&width=300",
    prepTime: 10,
    cookTime: 5,
    servings: 1,
    difficulty: "easy",
    rating: 4.6,
    reviews: 67,
    category: "breakfast",
    tags: ["vegetarian", "healthy", "quick"],
    calories: 320,
    protein: 12,
    carbs: 28,
    fat: 18,
    ingredients: [
      "2 slices whole grain bread",
      "1 ripe avocado",
      "1 egg",
      "1/4 cup cherry tomatoes, halved",
      "1 tsp everything bagel seasoning",
      "1 tsp lemon juice",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Toast bread slices until golden brown.",
      "Mash avocado with lemon juice, salt, and pepper.",
      "Poach egg in simmering water for 3-4 minutes.",
      "Spread avocado mixture on toast.",
      "Top with cherry tomatoes and poached egg.",
      "Sprinkle with everything bagel seasoning.",
      "Serve immediately.",
    ],
    isFavorite: false,
  },
  {
    id: "5",
    name: "Thai Green Curry",
    description: "Authentic Thai green curry with coconut milk, vegetables, and aromatic herbs and spices.",
    image: "/placeholder.svg?height=200&width=300",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: "medium",
    rating: 4.8,
    reviews: 92,
    category: "dinner",
    tags: ["dairy-free", "gluten-free", "spicy"],
    calories: 450,
    protein: 18,
    carbs: 35,
    fat: 28,
    ingredients: [
      "2 tbsp green curry paste",
      "1 can coconut milk",
      "1 lb chicken, sliced",
      "1 eggplant, cubed",
      "1 bell pepper, sliced",
      "1/4 cup Thai basil",
      "2 tbsp fish sauce",
      "1 tbsp brown sugar",
      "Jasmine rice for serving",
    ],
    instructions: [
      "Heat 1/4 cup coconut milk in a large pan.",
      "Add curry paste and cook until fragrant.",
      "Add chicken and cook until no longer pink.",
      "Add remaining coconut milk, bring to simmer.",
      "Add vegetables and cook until tender.",
      "Season with fish sauce and brown sugar.",
      "Stir in Thai basil just before serving.",
      "Serve over jasmine rice.",
    ],
    isFavorite: true,
  },
  {
    id: "6",
    name: "Greek Yogurt Parfait",
    description: "Layered parfait with Greek yogurt, fresh berries, granola, and a drizzle of honey.",
    image: "/placeholder.svg?height=200&width=300",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "easy",
    rating: 4.5,
    reviews: 43,
    category: "breakfast",
    tags: ["vegetarian", "healthy", "no-cook"],
    calories: 280,
    protein: 20,
    carbs: 35,
    fat: 8,
    ingredients: [
      "1 cup Greek yogurt",
      "1/4 cup granola",
      "1/2 cup mixed berries",
      "1 tbsp honey",
      "1 tsp chia seeds (optional)",
    ],
    instructions: [
      "Layer half the yogurt in a glass or bowl.",
      "Add half the berries and granola.",
      "Repeat layers with remaining ingredients.",
      "Drizzle with honey and sprinkle chia seeds.",
      "Serve immediately or chill until ready to eat.",
    ],
    isFavorite: false,
  },
];

export const mockShoppingList: ShoppingListItem[] = [
  {
    name: "Bananas",
    quantity: "6 pcs",
    price: "£1.20",
    category: "Produce",
  },
  {
    name: "Milk",
    quantity: "2 L",
    price: "£1.60",
    category: "Dairy & Eggs",
  },
  {
    name: "Chicken Breast",
    quantity: "500 g",
    price: "£3.75",
    category: "Meat",
  },
  {
    name: "Frozen Peas",
    quantity: "1 kg",
    price: "£2.00",
    category: "Frozen",
  },
  {
    name: "Wholemeal Bread",
    quantity: "1 loaf",
    price: "£1.10",
    category: "Bakery",
  },
  {
    name: "Orange Juice",
    quantity: "1 L",
    price: "£1.50",
    category: "Beverages",
  },
  {
    name: "Toilet Paper",
    quantity: "12 rolls",
    price: "£4.99",
    category: "Household",
  },
  {
    name: "Eggs",
    quantity: "12 pcs",
    price: "£2.20",
    category: "Dairy & Eggs",
  },
  {
    name: "Ground Beef",
    quantity: "400 g",
    price: "£3.20",
    category: "Meat",
  },
  {
    name: "Frozen Pizza",
    quantity: "1 pc",
    price: "£2.75",
    category: "Frozen",
  },
];

